#!/usr/bin/env Rscript

# Title: stats_ExN50.R
# Date: 2018-01-11
# Author: Adam Nunn
#
# Description:
#    This R script plots the change in contig N50 size in relation to the
#    quantile of most expressed transcripts that are considered when
#    evaluating the N50. The script takes a single input file: 1) the table
#    of values generated by the trinity script "contig_ExN50_statistic.pl"
#    (INPUT_N50_FILE). The script will output the graph to the file
#    "ExN50.pdf" in the current directory.
#
# Usage:
#     Rscript stats_ExN50.R INPUT_N50_FILE
# eg. Rscript stats_ExN50.R ExN50.stats
#

args <- commandArgs(trailingOnly=T)
data <- read.table(args[1])
data$V1 <- as.integer(gsub('E', '', data$V1))
pdf("ExN50.pdf")
plot(data$V3~data$V1, t='b', col='blue', xlab="Ex", ylab="ExN50")
dev.off()
